# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Frontend (Next.js + Jest + Cypress) CI

on:
  pull_request:
    branches: [ "main" ]
    
jobs:
  E2E-Tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Move to app directory
      run: cd app
      
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test:e2e

  Unit-Tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Move to app directory
      run: cd app
      
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test:unit
